// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "firstInstall": boolean;
      "automaticDownload": boolean;
      "sciHubURLs": string;
      "enableOpenAlex": boolean;
      "openAlexApiKey": string;
    };
  }
}
